name: product_management_getx
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  get: ^4.6.5
  dio: ^5.0.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  flutter_easyloading: ^3.0.5
  json_annotation: ^4.8.1
  flutter_test:
    sdk: flutter
  pull_to_refresh_flutter3: ^2.0.2

dev_dependencies:
  hive_generator: ^2.0.1
  build_runner: ^2.4.15
  json_serializable: ^6.7.1

flutter:
  uses-material-design: true